const CENTER = { x: 150, y: 100 }
const HEADER_RADIUS = 9.35
const HEADER_PITCH = 2.54;
const SCREW_RADIUS = 9.35
const CUT_RADIUS = 15
const CUT_SIDES = 6

module.exports = {
  CENTER,
  HEADER_RADIUS,
  HEADER_PITCH,
  SCREW_RADIUS,
  CUT_RADIUS,
  CUT_SIDES
}
